###register request
Post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "asdsdsdd6456",
    "email": "ehsan@gmail.com",
    "mobile": "09375338875",
    "password": "123456789",
    "confirm_password": "123456789"
}

###Login request
Post http://localhost:3000/auth/login
Content-Type: application/json
Authorization: {{$dotenv SECRET_KEY}}

{
    "username": "user1",
    "password": "123456789"
}
